### ISSUE TITLE
It should be possible to keep the trajectory file on the remote system

### ISSUE THREAD

**Issue by LourensVeen** [MD-Studio/lie_md#9]
- Give the lie_md microservice an extra optional argument to pass a path to store the file at
- Add a step to the CWL API that saves an input file to a path
- Update specializations
- Extend the CWL workflow with a step that optionally saves an input file to a path (if possible)
- Fix lie_md to do this

**Comment by marcvdijk** [comment]
This is temporary fixed by adding a 'clean_remote_workdir' option to the lie_md endpoint that instructs Cerise to (not) remove the remote job directory in .cerise/jobs. This will not copy the results to any user specified store location but at least the data is still available.

I will close this issue for now.
